//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTransform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazorTransform.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{1}&quot; not found for enum &quot;{0}&quot;.
        /// </summary>
        internal static string BadEnum {
            get {
                return ResourceManager.GetString("BadEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a number: &quot;{1}&quot;.
        /// </summary>
        internal static string BadInteger {
            get {
                return ResourceManager.GetString("BadInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtValues version not supported: {0}.
        /// </summary>
        internal static string BadRtValueVersion {
            get {
                return ResourceManager.GetString("BadRtValueVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder for transformed files.  Use context menu to create a new folder..
        /// </summary>
        internal static string BrowsePrompt {
            get {
                return ResourceManager.GetString("BrowsePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel processing.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the application.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RazorTransform complete..
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save with invalid data?.
        /// </summary>
        internal static string ConfirmDirtySave {
            get {
                return ResourceManager.GetString("ConfirmDirtySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the PowerShell?.
        /// </summary>
        internal static string ConfirmPowerShellCancel {
            get {
                return ResourceManager.GetString("ConfirmPowerShellCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion complete..
        /// </summary>
        internal static string ConversionComplete {
            get {
                return ResourceManager.GetString("ConversionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} to the clipboard.
        /// </summary>
        internal static string CopyContextMenu {
            get {
                return ResourceManager.GetString("CopyContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of this item that can be used elsewhere in Artie.  If the ordering changes, this will be invalid..
        /// </summary>
        internal static string CopyIndexTooltip {
            get {
                return ResourceManager.GetString("CopyIndexTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of this item that can be used elsewhere in Artie.  If the key changes, this will be invalid..
        /// </summary>
        internal static string CopyNameTooltip {
            get {
                return ResourceManager.GetString("CopyNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder must exist. {0}.
        /// </summary>
        internal static string DestMustExist {
            get {
                return ResourceManager.GetString("DestMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting on enum {0}&apos;s script &quot;{1}&quot; to run..
        /// </summary>
        internal static string EnumScriptTimeout {
            get {
                return ResourceManager.GetString("EnumScriptTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create object from .
        /// </summary>
        internal static string ErrorCreatingCustom {
            get {
                return ResourceManager.GetString("ErrorCreatingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two one-parameter constructors, one with Model, one with string are ambiguous in custom type: .
        /// </summary>
        internal static string ErrorCreatingCustomAmbiguous {
            get {
                return ResourceManager.GetString("ErrorCreatingCustomAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching constructor found for custom class: .
        /// </summary>
        internal static string ErrorCreatingCustomConstructor {
            get {
                return ResourceManager.GetString("ErrorCreatingCustomConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create custom type from.
        /// </summary>
        internal static string ErrorCustomType {
            get {
                return ResourceManager.GetString("ErrorCustomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing enum script &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string ErrorInEnumScript {
            get {
                return ResourceManager.GetString("ErrorInEnumScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading child XML file {0}: {1}.
        /// </summary>
        internal static string ErrorLoadingChildXml {
            get {
                return ResourceManager.GetString("ErrorLoadingChildXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class on custom named.
        /// </summary>
        internal static string ErrorNullCustomClassName {
            get {
                return ResourceManager.GetString("ErrorNullCustomClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name on custom.
        /// </summary>
        internal static string ErrorNullCustomName {
            get {
                return ResourceManager.GetString("ErrorNullCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name on enum.
        /// </summary>
        internal static string ErrorNullEnumName {
            get {
                return ResourceManager.GetString("ErrorNullEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx configuration must have name and value.
        /// </summary>
        internal static string ErrorNullRegEx {
            get {
                return ResourceManager.GetString("ErrorNullRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!
        ///{0}.
        /// </summary>
        internal static string ExceptionFormat {
            get {
                return ResourceManager.GetString("ExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded value:.
        /// </summary>
        internal static string ExpandedValue {
            get {
                return ResourceManager.GetString("ExpandedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; not found.
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}RazorTranformation Tool transforms an object described in &lt;objectFile&gt;into all the files in a &lt;templateFolder&gt;
        ///
        ///Command line options are:
        ///   [-run] [-object &lt;objectFile&gt;] [-values &lt;valuesFile&gt;] [-output &lt;outputFolder&gt;] [-template &lt;templateFolder&gt; [-logFile &lt;logFile&gt;] [-test] [-nosave]  [-powerShell]  [-exportPs] [-h|-?] [&lt;overrides....&gt;]
        ///
        ///   -h -? show this help
        ///  -test runs the transforms without saving the output to make sure Razor views work
        ///  -nosave does not save the override values in &lt;objec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Index out of range for &quot;{0}&quot;: {1}[{2}]&quot;.
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array &quot;{0}&quot; specified in the object file for EnumFromArray &quot;{1}&quot; was not found..
        /// </summary>
        internal static string InvalidArrayName {
            get {
                return ResourceManager.GetString("InvalidArrayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enum &quot;{0}&quot; specified in the object file for EnumFromArray &quot;{1}&quot; was not found..
        /// </summary>
        internal static string InvalidEnumName {
            get {
                return ResourceManager.GetString("InvalidEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script specified in enum {0}, &quot;{1}&quot; was not found..
        /// </summary>
        internal static string InvalidEnumScript {
            get {
                return ResourceManager.GetString("InvalidEnumScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Uri: .
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes in {0}?.
        /// </summary>
        internal static string IsDirty {
            get {
                return ResourceManager.GetString("IsDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has {2} items, but must have no more than {1}..
        /// </summary>
        internal static string MaxCount {
            get {
                return ResourceManager.GetString("MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is {2} but must be less than {3}..
        /// </summary>
        internal static string MaxInt {
            get {
                return ResourceManager.GetString("MaxInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; with a value of &quot;{1}&quot; must contain no more than {3} characters, but has {2}..
        /// </summary>
        internal static string MaxStrLen {
            get {
                return ResourceManager.GetString("MaxStrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has {2} items, but must have at least {1}..
        /// </summary>
        internal static string MinCount {
            get {
                return ResourceManager.GetString("MinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is {1} but must be greater than {3}. .
        /// </summary>
        internal static string MinInt {
            get {
                return ResourceManager.GetString("MinInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; with a value of &quot;{1}&quot; must contain at least {3} characters, but has {2}..
        /// </summary>
        internal static string MinStrLen {
            get {
                return ResourceManager.GetString("MinStrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found for enum {0} after executing script &quot;{1}&quot;.
        /// </summary>
        internal static string NoEnumContent {
            get {
                return ResourceManager.GetString("NoEnumContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave option specified that prevented saving values..
        /// </summary>
        internal static string NoSave {
            get {
                return ResourceManager.GetString("NoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorProcessing {0}:
        ///{1}.
        /// </summary>
        internal static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing transforms....
        /// </summary>
        internal static string ProcessingTransforms {
            get {
                return ResourceManager.GetString("ProcessingTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is {1} but must be between {3} and {4}..
        /// </summary>
        internal static string RangeInt {
            get {
                return ResourceManager.GetString("RangeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has a value of &quot;{1}&quot; and length of {2} but length must be between {3} and {4}.
        /// </summary>
        internal static string RangeStrLen {
            get {
                return ResourceManager.GetString("RangeStrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression &quot;{0}&quot; not found in configuration.
        /// </summary>
        internal static string RegExNotFound {
            get {
                return ResourceManager.GetString("RegExNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; with a value of &quot;{2}&quot; does not match pattern &quot;{1}&quot;.
        /// </summary>
        internal static string RegExViolation {
            get {
                return ResourceManager.GetString("RegExViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting PowerShell processing....
        /// </summary>
        internal static string RunningPowerShell {
            get {
                return ResourceManager.GetString("RunningPowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning dependents.
        /// </summary>
        internal static string ScanningDependents {
            get {
                return ResourceManager.GetString("ScanningDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing after exception loading settings: {0}.
        /// </summary>
        internal static string SettingsException {
            get {
                return ResourceManager.GetString("SettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RazorTransform starting....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting transforms.
        /// </summary>
        internal static string StartingTransforms {
            get {
                return ResourceManager.GetString("StartingTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Processed {0} files in {2:f2} secs to {1}.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template folder &quot;{0}&quot; not found..
        /// </summary>
        internal static string TemplateFolderNotFound {
            get {
                return ResourceManager.GetString("TemplateFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test mode specified.  No data was written out.
        /// </summary>
        internal static string TestModeComplete {
            get {
                return ResourceManager.GetString("TestModeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST MODE.  NO DATA WILL BE WRITTEN OUT..
        /// </summary>
        internal static string TestModeLogStart {
            get {
                return ResourceManager.GetString("TestModeLogStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razor Transform Tool.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform of &quot;{0}&quot; returned no content.
        /// </summary>
        internal static string TransformNoContent {
            get {
                return ResourceManager.GetString("TransformNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non unique name : &quot;{0}&quot;.
        /// </summary>
        internal static string UniqueViolation {
            get {
                return ResourceManager.GetString("UniqueViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameters: {0}
        ///
        ///.
        /// </summary>
        internal static string UnknownCommands {
            get {
                return ResourceManager.GetString("UnknownCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating values.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the following before continuing:
        ///{0}.
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
    }
}
