//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTransform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazorTransform.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a number: &quot;{1}&quot;.
        /// </summary>
        internal static string BadInteger {
            get {
                return ResourceManager.GetString("BadInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtValues version not supported: {0}.
        /// </summary>
        internal static string BadRtValueVersion {
            get {
                return ResourceManager.GetString("BadRtValueVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder for transformed files.  Use context menu to create a new folder..
        /// </summary>
        internal static string BrowsePrompt {
            get {
                return ResourceManager.GetString("BrowsePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion complete..
        /// </summary>
        internal static string ConversionComplete {
            get {
                return ResourceManager.GetString("ConversionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder must exist. {0}.
        /// </summary>
        internal static string DestMustExist {
            get {
                return ResourceManager.GetString("DestMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create object from .
        /// </summary>
        internal static string ErrorCreatingCustom {
            get {
                return ResourceManager.GetString("ErrorCreatingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two one-parameter constructors, one with Model, one with string are ambiguous in custom type: .
        /// </summary>
        internal static string ErrorCreatingCustomAmbiguous {
            get {
                return ResourceManager.GetString("ErrorCreatingCustomAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching constructor found for custom class: .
        /// </summary>
        internal static string ErrorCreatingCustomConstructor {
            get {
                return ResourceManager.GetString("ErrorCreatingCustomConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create custom type from.
        /// </summary>
        internal static string ErrorCustomType {
            get {
                return ResourceManager.GetString("ErrorCustomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading child XML file {0}: {1}.
        /// </summary>
        internal static string ErrorLoadingChildXml {
            get {
                return ResourceManager.GetString("ErrorLoadingChildXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class on custom named.
        /// </summary>
        internal static string ErrorNullCustomClassName {
            get {
                return ResourceManager.GetString("ErrorNullCustomClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name on custom.
        /// </summary>
        internal static string ErrorNullCustomName {
            get {
                return ResourceManager.GetString("ErrorNullCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name on enum.
        /// </summary>
        internal static string ErrorNullEnumName {
            get {
                return ResourceManager.GetString("ErrorNullEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx configuration must have name and value.
        /// </summary>
        internal static string ErrorNullRegEx {
            get {
                return ResourceManager.GetString("ErrorNullRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!
        ///{0}.
        /// </summary>
        internal static string ExceptionFormat {
            get {
                return ResourceManager.GetString("ExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded value:.
        /// </summary>
        internal static string ExpandedValue {
            get {
                return ResourceManager.GetString("ExpandedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; not found.
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RazorTranformation Tool transforms an object described in &lt;objectFile&gt;into all the files in a &lt;templateFolder&gt;
        ///
        ///Command line options are:
        ///   [-run] [-object &lt;objectFile&gt;] [-values &lt;valuesFile&gt;] [-output &lt;outputFolder&gt;] [-template &lt;templateFolder&gt; [-logFile &lt;logFile&gt;] [-test] [-nosave] [-h|-?] [&lt;overrides....&gt;] 
        ///
        ///   -h -? show this help
        ///  -test runs the transforms without saving the output to make sure Razor views work
        ///  -nosave does not save the override values in &lt;objectFile&gt;, useful when using over [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Uri: .
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes in {0}?.
        /// </summary>
        internal static string IsDirty {
            get {
                return ResourceManager.GetString("IsDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.
        /// </summary>
        internal static string MaxInt {
            get {
                return ResourceManager.GetString("MaxInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can contain no more than {1} characters .
        /// </summary>
        internal static string MaxStrLen {
            get {
                return ResourceManager.GetString("MaxStrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have at least {1} items.
        /// </summary>
        internal static string MinCount {
            get {
                return ResourceManager.GetString("MinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        internal static string MinInt {
            get {
                return ResourceManager.GetString("MinInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have at least {1} characters long.
        /// </summary>
        internal static string MinStrLen {
            get {
                return ResourceManager.GetString("MinStrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave option specified that prevented saving values..
        /// </summary>
        internal static string NoSave {
            get {
                return ResourceManager.GetString("NoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorProcessing {0}:
        ///{1}.
        /// </summary>
        internal static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing transforms....
        /// </summary>
        internal static string ProcessingTransforms {
            get {
                return ResourceManager.GetString("ProcessingTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression &quot;{0}&quot; not found in configuration.
        /// </summary>
        internal static string RegExNotFound {
            get {
                return ResourceManager.GetString("RegExNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &quot;{0}&quot; does not match pattern &quot;{1}&quot;.
        /// </summary>
        internal static string RegExViolation {
            get {
                return ResourceManager.GetString("RegExViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting PowerShell processing....
        /// </summary>
        internal static string RunningPowerShell {
            get {
                return ResourceManager.GetString("RunningPowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning dependents.
        /// </summary>
        internal static string ScanningDependents {
            get {
                return ResourceManager.GetString("ScanningDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing after exception loading settings: {0}.
        /// </summary>
        internal static string SettingsException {
            get {
                return ResourceManager.GetString("SettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting transforms.
        /// </summary>
        internal static string StartingTransforms {
            get {
                return ResourceManager.GetString("StartingTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Processed {0} files in {2:f2} secs to {1}.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test mode specified.  No data was written out.
        /// </summary>
        internal static string TestModeComplete {
            get {
                return ResourceManager.GetString("TestModeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST MODE.  NO DATA WILL BE WRITTEN OUT..
        /// </summary>
        internal static string TestModeLogStart {
            get {
                return ResourceManager.GetString("TestModeLogStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razor Transform Tool.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform of &quot;{0}&quot; returned no content.
        /// </summary>
        internal static string TransformNoContent {
            get {
                return ResourceManager.GetString("TransformNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non unique name : &quot;{0}&quot;.
        /// </summary>
        internal static string UniqueViolation {
            get {
                return ResourceManager.GetString("UniqueViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating values.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct the following before continuing:
        ///{0}.
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
    }
}
