# Generated by tool on @DateTime.Now
# script to create all the databases
try
{
	$logFolder = $PWD
	Push-Location "@Model.ScriptFilePath"
	@foreach( var t in @Model.Tenants){
	@:.\createAllDatabases.ps1 -instance "@Model.InstanceName" -tenant "@t.name" -tenantDescription "@t.description" -sqlAdminUser "@Model.SQLUser" -controlId "@t.controlId" -server "@Model.SQLServer" -fileLocation "@Model.DatabaseFilePath" -scriptLocation "@Model.ScriptFilePath" -version "@Model.Version" -logFolder $logFolder 
	}
}
finally
{
Pop-Location
}
